---
title: "Análisis de sentimientos 2021"
author: "Mauro Rodriguez"
date: "enero 07 , 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#install.packages(rtweet)

#install.packages(httpuv)

library(rtweet)
library(httpuv)
```

```{r}
getwd()
```


```{r}
## authenticate via access token

token <- create_token(
  app = "my_twitter_analysis_for_R ",

  consumer_key = "cxBFTIkDS2nWOOcCEP68fGQuC",
  consumer_secret = "Tu3mgZWanbDQ0x7q6Pxi4nFBHDQZnOPHjn6Npos5PjO48mToj1",
  access_token = "137117751-EyN8p1NOsRJABAPsgimqHLl34m8QfRswamNWK1EE",
  access_secret = "8tzr1HyFjeSuLdfFELVHqMEMipZRReKigwWjzz1jeXoTM")

```

```{r}

  ## check to see if the token is loaded
identical(token, get_token())
```

```{r}
## search for 10000 tweets using the rstats hashtag
rt <- search_tweets(
  "#AMAZON", n = 10000, include_rts = FALSE
)
```

```{r}

## plot time series of tweets
rt %>%
  ts_plot("3 hours ") +
  ggplot2::theme_minimal() +
  ggplot2::theme(plot.title = ggplot2::element_text(face = "bold")) +
  ggplot2::labs(
    x = NULL, y = NULL,
    title = "Frequency of #AMAZON Hashtag from past 9 days",
    subtitle = "Twitter status (tweet) counts aggregated using three-hour intervals",
    caption = "\nSource: Data collected from Twitter's REST API via rtweet, Mauro Rodríguez PhD."
  )
```

```{r}
library(maps)
```

```{r}

## search for 10,000 tweets sent from the US
rt <- search_tweets(
  "lang:en", geocode = lookup_coords("usa"), n = 10000
)

## create lat/lng variables using all available tweet and profile geo-location data
rt <- lat_lng(rt)

## plot state boundaries
par(mar = c(0, 0, 0, 0))
maps::map("state", lwd = .25)

## plot lat and lng points onto state map
with(rt, points(lng, lat, pch = 20, cex = .75, col = rgb(0, .3, .7, .75)))

```


```{r}
rt_sent <- rt$text %>% 
    syuzhet::get_nrc_sentiment()

head(rt_sent) %>% 
  knitr::kable(caption = "Twitter Sentiment")

```

```{r}
library(dplyr)
```


```{r}
rt_sent %>% 
  summarize_all(sum, na.rm = TRUE) %>% 
  select(-negative, -positive) %>% # Dropping these helps in plotting
  reshape2::melt() %>% 
  ggplot(aes(reorder(variable, -value), value)) +
  geom_col() +
  labs(x = "Sentiment", y = "Frequency of Words") +
  theme_minimal()
## No id variables; using all as measure variables

```


```{r}

library(dplyr)
rt_sent %>% 
  summarize_all(sum, na.rm = TRUE) %>% 
  select(negative, positive) %>% 
  reshape2::melt() %>% 
  ggplot(aes(reorder(variable, -value), value)) +
  geom_col() +
  labs(x = "Sentiment", y = "Frequency of Words") +
  theme_minimal()
```

