---
title: "Bass model iPad"
author: "Mauro Rodríguez"
date: "1/11/2021"
output: html_document
---



```{r}

Sales<-read.csv("iPad.csv")

Sales
```

```{r}
Sales=ts(Sales,start=c(2014,3),freq=4)
```

```{r}
#Plot data
library(ggplot2) 
plot(Sales,type="l",lty=2, col="red", ylab="", xlab="")
points(Sales,pch=20, col="blue")
title("Quarterly sales (millions)")
```


```{r}
#Plot cumulative sales

Y=cumsum(Sales)
Y=ts(Y,start=c(2014,3),freq=4)
plot(Y,type="l", lty=2, col="red", ylab="",xlab="")
points(Y,pch=20,col="blue")
title("Cumulative sales (millions)")
```

```{r}
#Bass model and compute m,p,q
Y=c(0,Y[1:(length(Y)-1)])
Ysq=Y**2
out=lm(Sales~Y+Ysq)
summary(out)
a=out$coef[1]
b=out$coef[2]
c=out$coef[3]
mplus=(-b+sqrt(b**2-4*a*c))/(2*c)
mminus=(-b-sqrt(b**2-4*a*c))/(2*c)
m=mminus
p=1/m
q=b+p


```


```{r}
#Compute Bass Model
bassModel=function(p,q,m,T=100)
{
  S=double(T)
  Y=double(T+1)
  Y[1]=0
  for(t in 1:T)
  {
    S[t]=p*m+(q-p)*Y[t]-(q/m)*Y[t]**2
  Y[t+1]=Y[t]+S[t]
  }
  return(list(sales=S,cumSales=cumsum(S)))
}

Spred=bassModel(p,q,m,T=23)$sales

Spred=ts(Spred,start=c(2014,3),freq=4)


```



```{r}


ts.plot(Sales,Spred,col=c("blue","red"))
legend("topleft", legend=c("Actual", "Bass Model"),fill=c("blue","red"))


```

```{r}
#Proyection

Spred=bassModel(p,q,m)$sales
CumSpred=ts(cumsum(Spred),start=c(2014,3),freq=4)
CumSales=ts(cumsum(Sales),start=c(2014,3),freq=4)
ts.plot(CumSales,CumSpred,col=c("blue","red"))
legend("topleft", legend=c("Actual", "Bass Model"),fill=c("blue","red"))
title("Predicted Cumulative Sales IPads")
```


